#ifndef KYROS_VERSION_H
#define KYROS_VERSION_H

#define KYROS_VERSION_MAJOR 26
#define KYROS_VERSION_MINOR 01
#define KYROS_VERSION_PATCH 00
#define KYROS_VERSION_BUILD 0011
#define KYROS_VERSION_CODENAME "Helium"

#endif // KYROS_VERSION_H
